"""
Seed content for the MAXEK India corporate website.

NOTE ON CONTENT PROVENANCE
--------------------------
Company identity, business structure, vertical names, service lists, taglines
and section copy are taken verbatim from the client PRD / Content Guide.

Project records, Knowledge Center articles and job openings are realistic,
industry-appropriate PLACEHOLDER records (approved by the client) so that every
page and flow is fully functional. They live in MongoDB and can be replaced
with real records without any code change.
"""

IMG = "https://images.unsplash.com"

# --------------------------------------------------------------------------
# PROJECTS
# --------------------------------------------------------------------------
PROJECTS = [
    {
        "slug": "foxconn-a11-facility",
        "title": "Foxconn A11 Facility",
        "vertical": "MAXEK INFRA",
        "vertical_slug": "maxek-infra",
        "sector": "industrial",
        "type": "Industrial Manufacturing Facility",
        "industry": "Manufacturing",
        "location": "Walajabad, Kancheepuram, Tamil Nadu",
        "year": "2024",
        "status": "Completed",
        "featured": True,
        "project_value": "₹8 Crore",
        "summary": "Foxconn A11 Facility.",
        "overview": "Foxconn A11 Facility.",
        "image": "/assets/projects/FOXCONN A11 FACILITY.webp",
        "gallery": ["/assets/projects/FOXCONN A11 FACILITY.webp"]
    },
    {
        "slug": "foxconn-a04-facility",
        "title": "Foxconn A04 Facility",
        "vertical": "MAXEK INFRA",
        "vertical_slug": "maxek-infra",
        "sector": "industrial",
        "type": "Industrial Manufacturing Facility",
        "industry": "Manufacturing",
        "location": "Walajabad, Kancheepuram, Tamil Nadu",
        "year": "2024",
        "status": "Completed",
        "featured": True,
        "project_value": "₹5.5 Crore",
        "summary": "Foxconn A04 Facility.",
        "overview": "Foxconn A04 Facility.",
        "image": "/assets/projects/FOXCONN A04 FACILITY.webp",
        "gallery": ["/assets/projects/FOXCONN A04 FACILITY.webp"]
    },
    {
        "slug": "hilite-28-floor-tower",
        "title": "HiLITE 28-Floor Tower",
        "vertical": "MAXEK INFRA",
        "vertical_slug": "maxek-infra",
        "sector": "residential",
        "type": "28-Floor Luxury Residential Tower",
        "industry": "Real Estate",
        "location": "Kerala, India",
        "year": "2024",
        "status": "Completed",
        "featured": False,
        "project_value": "₹7 Crore",
        "summary": "HiLITE 28-Floor Tower.",
        "overview": "HiLITE 28-Floor Tower.",
        "image": "/assets/projects/HILITE 28-FLOOR TOWER.webp",
        "gallery": ["/assets/projects/HILITE 28-FLOOR TOWER.webp"]
    },
    {
        "slug": "sattva-knowledge-city",
        "title": "Sattva Knowledge City",
        "vertical": "MAXEK INFRA",
        "vertical_slug": "maxek-infra",
        "sector": "commercial",
        "type": "Commercial IT & Business Park",
        "industry": "Commercial",
        "location": "Chennai, Tamil Nadu",
        "year": "2024",
        "status": "Completed",
        "featured": True,
        "project_value": "₹9.5 Crore",
        "summary": "Sattva Knowledge City.",
        "overview": "Sattva Knowledge City.",
        "image": "/assets/projects/SATTVA KNOWLEDGE CITY.webp",
        "gallery": ["/assets/projects/SATTVA KNOWLEDGE CITY.webp"]
    },
    {
        "slug": "kssia-one",
        "title": "KSSIA ONE",
        "vertical": "MAXEK SOLUTIONS",
        "vertical_slug": "maxek-solutions",
        "sector": "digital-platforms",
        "type": "Digital Platform / Association Member Platform",
        "industry": "Technology",
        "location": "Thiruvananthapuram, Kerala",
        "year": "2024",
        "status": "Completed",
        "featured": True,
        "client": "Kerala State Small Industries Association (KSSIA), Thiruvananthapuram District",
        "developed_by": "MAXEK Private Limited",
        "role": "Technology & Infrastructure Partner",
        "core_purpose": "Connecting Members. Strengthening Industry.",
        "summary": "Digital platform for KSSIA, Thiruvananthapuram District",
        "overview": "KSSIA ONE brings members, industry information, events, and member services together in one digital environment.",
        "about_platform": "KSSIA ONE brings members, industry information, events, and member services together in one digital environment.",
        "features": [
            "MEMBER DIRECTORY",
            "MEMBER SEARCH",
            "LIFE MEMBERS",
            "EVENTS & PROGRAMS",
            "EVENT DETAILS",
            "CLAIM / TRACK",
            "MEMBERSHIP RENEWAL",
            "NOTIFICATIONS",
            "MEMBER SERVICES"
        ],
        "who_it_serves": [
            "KSSIA members",
            "Life members",
            "Small and medium-scale industrialists",
            "Entrepreneurs",
            "Member businesses",
            "KSSIA district association stakeholders"
        ],
        "image": "/assets/projects/kssia.png",
        "videos": [
            {
                "src": "/assets/projects/kssia-app-building-intro.mp4",
                "title": "KSSIA ONE — Building Introduction"
            },
            {
                "src": "/assets/projects/kssia-building-forms.mp4",
                "title": "KSSIA ONE — Forms & Login Walkthrough"
            }
        ],
        "gallery": ["/assets/projects/kssia.png"]
    },
    {
        "slug": "recruitment-partner-people-excellence",
        "title": "Recruitment Partner™ & People Excellence™ Engagement",
        "vertical": "MAXEK BUSINESS HUB",
        "vertical_slug": "maxek-business-hub",
        "industry": "Industrial",
        "location": "India",
        "year": "2024",
        "status": "Ongoing",
        "featured": False,
        "summary": "Technical hiring and capability development delivered as one engagement for a scaling engineering firm.",
        "overview": "A scaling engineering firm struggling to hire technical talent quickly enough and losing capability through attrition. Recruitment Partner™ addressed the hiring pipeline while People Excellence™ built internal capability and retention.",
        "scope": [
            "Role definition and competency mapping",
            "Technical sourcing and structured screening",
            "Interview panel design and evaluation criteria",
            "Onboarding programme design",
            "Capability development pathways",
            "Retention and engagement framework",
        ],
        "challenges": [
            "Vacancies open for extended periods across technical disciplines.",
            "Unstructured interviews producing inconsistent hiring decisions.",
            "New joiners left to find their own way after day one.",
        ],
        "solutions": [
            "Built competency-mapped role definitions before sourcing began.",
            "Introduced a scored interview framework used by every panel.",
            "Designed a structured onboarding pathway with defined 30/60/90 day milestones.",
        ],
        "results": [
            "Time to fill technical roles materially reduced.",
            "Hiring decisions became consistent and defensible.",
            "New joiners reached productive contribution faster.",
        ],
        "image": f"{IMG}/photo-1758518731706-be5d5230e5a5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": [
            f"{IMG}/photo-1758518731706-be5d5230e5a5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            f"{IMG}/photo-1758518730037-a16581a040e8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
    },
    {
        "slug": "digital-transformation-business-systems",
        "title": "Digital Transformation™ & Business Systems™ Rollout",
        "vertical": "MAXEK BUSINESS HUB",
        "vertical_slug": "maxek-business-hub",
        "industry": "Commercial",
        "location": "India",
        "year": "2025",
        "status": "In Progress",
        "featured": False,
        "summary": "Core business processes documented, systemised and automated for a multi-branch operation.",
        "overview": "A multi-branch operation where each branch ran its own informal process. Digital Transformation™ and Business Systems™ established documented, systemised operations with automation applied to high-volume administrative work.",
        "scope": [
            "Current-state process mapping across branches",
            "Standard operating procedure development",
            "Business Systems™ implementation",
            "Business Automation™ for repetitive workflows",
            "Business Intelligence™ reporting layer",
            "Change management and adoption support",
        ],
        "challenges": [
            "Every branch operated a different informal process.",
            "Reporting required manual consolidation from each branch.",
            "Staff scepticism toward standardisation.",
        ],
        "solutions": [
            "Mapped all branch variants and designed one standard from the best elements.",
            "Automated consolidation so reporting no longer required manual collation.",
            "Involved branch representatives in designing the standard to build ownership.",
        ],
        "results": [
            "One documented standard operating model across all branches.",
            "Consolidated reporting produced automatically.",
            "Administrative workload reduced through targeted automation.",
        ],
        "image": f"{IMG}/photo-1758518730037-a16581a040e8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": [
            f"{IMG}/photo-1758518730037-a16581a040e8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            f"{IMG}/photo-1763038311036-6d18805537e5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
    },
    {
        "slug": "maxek-edu-corporate-training-programme",
        "title": "MAXEK EDU Corporate Training Programme",
        "vertical": "MAXEK BUSINESS HUB",
        "vertical_slug": "maxek-business-hub",
        "industry": "Education",
        "location": "India",
        "year": "2025",
        "status": "Ongoing",
        "featured": False,
        "summary": "A structured corporate learning programme combining AI literacy, business skills and certification.",
        "overview": "A corporate learning programme delivered through MAXEK EDU for an engineering organisation investing in workforce capability, blending AI literacy, business fundamentals and role-specific certification.",
        "scope": [
            "Skills gap assessment by role",
            "Curriculum design across three learning tracks",
            "AI Learning module development",
            "Workshop and instructor-led delivery",
            "Certification assessment framework",
            "Impact measurement and reporting",
        ],
        "challenges": [
            "Wide variation in baseline digital skills across the workforce.",
            "Training time competing directly with project delivery.",
            "No way to evidence capability gain after previous training.",
        ],
        "solutions": [
            "Assessed baseline skills and streamed learners into appropriate tracks.",
            "Delivered short modular sessions that fit around project commitments.",
            "Introduced certification assessments to evidence capability objectively.",
        ],
        "results": [
            "Measurable capability improvement recorded against assessments.",
            "Programme completed without disrupting project delivery.",
            "Certification records now support internal role progression.",
        ],
        "image": f"{IMG}/photo-1758691736424-4b4273948341?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": [
            f"{IMG}/photo-1758691736424-4b4273948341?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            f"{IMG}/photo-1579389083046-e3df9c2b3325?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
    },
]

# --------------------------------------------------------------------------
# KNOWLEDGE CENTER
# --------------------------------------------------------------------------
ARTICLES = [
    {
        "slug": "industrial-construction-programme-certainty",
        "title": "Building Programme Certainty into Industrial Construction",
        "category": "Industry Insights",
        "excerpt": "Programme slippage on industrial projects is rarely caused by one large event. It accumulates through decisions made long before mobilisation.",
        "author": "MAXEK INFRA",
        "published_on": "2025-11-18",
        "read_minutes": 6,
        "image": f"{IMG}/photo-1717386255773-1e3037c81788?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "tags": ["Industrial Construction", "Project Management", "Programme"],
        "related_vertical": "maxek-infra",
        "related_industry": "Industrial",
        "body": [
            {"type": "paragraph", "text": "Industrial projects are judged on a single question: was the facility ready when production needed it. Everything else, however well executed, is secondary to that date."},
            {"type": "heading", "text": "Slippage is cumulative, not sudden"},
            {"type": "paragraph", "text": "Programmes rarely fail because of one dramatic event. They fail through a series of small deferrals \u2014 a late design decision, an unconfirmed equipment dimension, a contractor mobilising a week behind. Each is individually recoverable. Together they consume the float that protects the commissioning date."},
            {"type": "heading", "text": "Four decisions that protect the date"},
            {"type": "list", "items": [
                "Fix the interface points early. Equipment foundations, service entry positions and load paths must be confirmed before the frame is committed.",
                "Move weather-sensitive work off the critical path. Off-site fabrication converts monsoon risk into a logistics question.",
                "Sequence into independent zones so trades can work concurrently instead of queuing.",
                "Run one interface review with every contractor against a shared look-ahead, not separate conversations.",
            ]},
            {"type": "heading", "text": "Engineering judgement over optimism"},
            {"type": "paragraph", "text": "A programme that assumes everything proceeds ideally is not a programme, it is a hope. Realistic durations with genuinely protected float deliver more certainty than an aggressive schedule that erodes in the first month."},
            {"type": "quote", "text": "Certainty is designed into a programme before mobilisation. It cannot be recovered afterwards through effort alone."},
        ],
    },
    {
        "slug": "erp-implementation-manufacturing-what-matters",
        "title": "ERP Implementation for Manufacturing: What Actually Determines Success",
        "category": "Technology Updates",
        "excerpt": "Most ERP programmes are not undone by software limitations. They are undone by master data, process ambiguity and adoption.",
        "author": "MAXEK SOLUTIONS",
        "published_on": "2025-11-04",
        "read_minutes": 7,
        "image": f"{IMG}/photo-1763038311036-6d18805537e5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "tags": ["ERP", "Manufacturing", "Digital Transformation"],
        "related_vertical": "maxek-solutions",
        "related_industry": "Manufacturing",
        "body": [
            {"type": "paragraph", "text": "Manufacturing organisations usually evaluate ERP platforms on feature comparison. In practice, the platform is rarely the deciding factor in whether the implementation succeeds."},
            {"type": "heading", "text": "Master data comes before configuration"},
            {"type": "paragraph", "text": "Duplicate item codes, inconsistent units of measure and overlapping vendor records will reproduce themselves faithfully inside a new system. Cleansing master data is unglamorous work, and it is the single highest-return activity in the entire programme."},
            {"type": "heading", "text": "Document the process you actually run"},
            {"type": "paragraph", "text": "Configuring against an idealised process guarantees workarounds. Map how procurement, stores and production genuinely operate today, then decide deliberately what should change."},
            {"type": "list", "items": [
                "Cleanse and consolidate master data before configuration starts.",
                "Document the real process, then design the intended process explicitly.",
                "Train by role, on the screens each person will actually use.",
                "Plan cutover so production is never dependent on a single switchover moment.",
            ]},
            {"type": "heading", "text": "Adoption is the deliverable"},
            {"type": "paragraph", "text": "An ERP that is bypassed is worse than no ERP, because it creates a false record. Role-specific training, visible floor-level support and a parallel-run cutover are what convert a technical go-live into an operational one."},
        ],
    },
    {
        "slug": "ai-solutions-for-industrial-businesses",
        "title": "Where AI Genuinely Helps Industrial Businesses Today",
        "category": "Articles",
        "excerpt": "Beyond the discourse, there are specific industrial problems where applied AI already delivers measurable operational value.",
        "author": "MAXEK SOLUTIONS",
        "published_on": "2025-10-21",
        "read_minutes": 6,
        "image": f"{IMG}/photo-1716191299980-a6e8827ba10b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "tags": ["AI Solutions", "Industrial Technology", "Data Analytics"],
        "related_vertical": "maxek-solutions",
        "related_industry": "Technology",
        "body": [
            {"type": "paragraph", "text": "The useful question for an industrial business is not whether to adopt AI, but which specific decisions are currently made with incomplete information."},
            {"type": "heading", "text": "Problems that suit applied AI"},
            {"type": "list", "items": [
                "Early-warning detection on project variance, where slippage patterns are visible in data before they are visible in reports.",
                "Quality event classification, grouping recurring defects that manual review treats as unrelated.",
                "Demand and consumption forecasting to reduce both stockouts and excess inventory.",
                "Document and drawing interrogation, where answers exist but are buried across revisions.",
            ]},
            {"type": "heading", "text": "Data readiness sets the ceiling"},
            {"type": "paragraph", "text": "Every one of those applications depends on consistent, structured operational data. Organisations that first fix capture \u2014 structured progress reporting, a common downtime taxonomy, governed master data \u2014 find applied AI straightforward. Those that skip it find it impossible."},
            {"type": "heading", "text": "Start where the decision is"},
            {"type": "paragraph", "text": "Choose one recurring decision, instrument the data behind it, and measure whether the decision improved. That is a far better starting point than a broad transformation mandate."},
        ],
    },
    {
        "slug": "steel-fabrication-quality-control",
        "title": "Quality Control in Steel Fabrication: From Shop to Erection",
        "category": "Case Studies",
        "excerpt": "Tolerance is decided in the shop, not on site. A look at the control points that determine whether steel erects first time.",
        "author": "MAXEK INFRA",
        "published_on": "2025-10-07",
        "read_minutes": 5,
        "image": f"{IMG}/photo-1698664683348-f9f35b809821?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "tags": ["Steel Fabrication", "Structural Engineering", "Quality"],
        "related_vertical": "maxek-infra",
        "related_industry": "Industrial",
        "body": [
            {"type": "paragraph", "text": "When structural steel does not fit on site, the cause is almost always upstream. Erection simply reveals decisions already taken in the fabrication shop."},
            {"type": "heading", "text": "Control points that matter"},
            {"type": "list", "items": [
                "Shop drawing verification against the coordinated model, not against the previous revision.",
                "Material traceability from mill certificate through to erected member.",
                "Weld procedure qualification and welder certification recorded per joint type.",
                "Dimensional inspection before coating, when correction is still inexpensive.",
                "Survey-controlled erection with staged alignment verification.",
            ]},
            {"type": "heading", "text": "Crane gantries raise the bar"},
            {"type": "paragraph", "text": "Overhead travelling crane systems demand tolerances tighter than general structural allowances. Achieving them requires survey control during erection and alignment verification before rails are fixed \u2014 not corrective work afterwards."},
            {"type": "heading", "text": "Sequence fabrication to erection"},
            {"type": "paragraph", "text": "Fabricating in erection sequence means steel arrives in build order. It removes double handling, reduces laydown pressure on constrained sites, and keeps the erection crew productive."},
        ],
    },
    {
        "slug": "digital-engineering-factory-infrastructure",
        "title": "Digital Engineering in Factory Infrastructure Projects",
        "category": "Industry Insights",
        "excerpt": "Coordinated models and structured data reduce rework on factory projects more reliably than additional site supervision.",
        "author": "MAXEK",
        "published_on": "2025-09-23",
        "read_minutes": 6,
        "image": f"{IMG}/photo-1767294274634-613a3545e36d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "tags": ["Digital Engineering", "Factory Infrastructure", "Innovation"],
        "related_vertical": "maxek-solutions",
        "related_industry": "Manufacturing",
        "body": [
            {"type": "paragraph", "text": "Factory projects are dense with interfaces. Structure, process equipment, utilities and safety systems all compete for the same physical space, and clashes discovered on site are expensive to resolve."},
            {"type": "heading", "text": "Resolve clashes where they are cheap"},
            {"type": "paragraph", "text": "A coordinated model moves clash resolution from the site to the desk. A service route that conflicts with a structural member costs minutes to move in a model and days to move once installed."},
            {"type": "heading", "text": "Structured data outlives the project"},
            {"type": "list", "items": [
                "As-built records tied to a model rather than a folder of drawings.",
                "Asset data captured at installation, ready for maintenance systems.",
                "Change history that is traceable rather than reconstructed.",
            ]},
            {"type": "heading", "text": "Engineering discipline, not software"},
            {"type": "paragraph", "text": "The value is not in the tooling. It comes from insisting that decisions are recorded once, in a place everyone works from \u2014 which is a discipline question before it is a technology one."},
        ],
    },
    {
        "slug": "business-growth-frameworks-for-smes",
        "title": "Structuring Growth: Frameworks That Work for Indian SMEs",
        "category": "Articles",
        "excerpt": "Growth stalls when informal processes that worked at ten people are still in use at a hundred.",
        "author": "MAXEK BUSINESS HUB",
        "published_on": "2025-09-09",
        "read_minutes": 5,
        "image": f"{IMG}/photo-1758518730083-4c12527b6742?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "tags": ["Business Growth", "Business Systems", "Strategy"],
        "related_vertical": "maxek-business-hub",
        "related_industry": "Commercial",
        "body": [
            {"type": "paragraph", "text": "Most SMEs do not stall because demand disappears. They stall because the informal coordination that worked at ten people cannot carry a hundred."},
            {"type": "heading", "text": "Three constraints that appear together"},
            {"type": "list", "items": [
                "Acquisition depends on relationships held by a few individuals rather than a repeatable channel.",
                "Delivery quality varies because the process lives in people's heads, not in a documented standard.",
                "Management reporting requires manual consolidation, so decisions are made on stale information.",
            ]},
            {"type": "heading", "text": "Systemise before scaling"},
            {"type": "paragraph", "text": "Scaling an undocumented process multiplies inconsistency. Documenting the standard first \u2014 then automating the repetitive parts of it \u2014 means growth adds volume rather than chaos."},
            {"type": "heading", "text": "Involve the people who run it"},
            {"type": "paragraph", "text": "Standards written without the people who execute them are ignored. Designing the standard with branch and team representatives builds the ownership that makes adoption real."},
        ],
    },
    {
        "slug": "maxek-corporate-profile-download",
        "title": "MAXEK Corporate Profile",
        "category": "Downloads",
        "excerpt": "An overview of MAXEK India Private Limited, our three business verticals, capabilities and engineering approach.",
        "author": "MAXEK",
        "published_on": "2025-08-26",
        "read_minutes": 2,
        "image": f"{IMG}/photo-1690944851207-3f288c8fcd0b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "tags": ["Corporate Profile", "MAXEK", "Downloads"],
        "related_vertical": None,
        "related_industry": None,
        "download_url": "request",
        "body": [
            {"type": "paragraph", "text": "The MAXEK Corporate Profile summarises our organisation, business verticals, capabilities and engineering approach in a single document for evaluation and procurement teams."},
            {"type": "heading", "text": "What the profile covers"},
            {"type": "list", "items": [
                "Company overview and organisational structure",
                "MAXEK INFRA \u2014 engineering and industrial execution capabilities",
                "MAXEK SOLUTIONS \u2014 technology and digital engineering capabilities",
                "MAXEK BUSINESS HUB \u2014 business growth ecosystem and MAXEK EDU",
                "Engineering approach, quality and safety commitments",
                "Industries served and representative project experience",
            ]},
            {"type": "paragraph", "text": "Request the current edition through the enquiry form and our team will share it directly with you."},
        ],
    },
    {
        "slug": "maxek-media-and-announcements",
        "title": "MAXEK Media & Announcements",
        "category": "Media",
        "excerpt": "Official announcements, media resources and brand assets relating to MAXEK India Private Limited.",
        "author": "MAXEK",
        "published_on": "2025-08-12",
        "read_minutes": 2,
        "image": f"{IMG}/photo-1686676104932-3d7b6bbaef52?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "tags": ["Media", "MAXEK", "Announcements"],
        "related_vertical": None,
        "related_industry": None,
        "body": [
            {"type": "paragraph", "text": "This section carries official MAXEK announcements and media resources. For interview requests, media enquiries or brand asset access, contact our team directly."},
            {"type": "heading", "text": "Media enquiries"},
            {"type": "list", "items": [
                "Business and media enquiries: info@maxekindia.com",
                "Telephone: +91 9666822000",
                "Registered office: Singapore Plaza, Pattom Palace, Thiruvananthapuram, Kerala \u2013 695004",
            ]},
            {"type": "paragraph", "text": "Official MAXEK logos and brand assets must be reproduced without modification. Please contact us before publication to confirm you are using the current versions."},
        ],
    },
]

# --------------------------------------------------------------------------
# CAREERS
# --------------------------------------------------------------------------
JOBS = [
    {
        "id": "erp-ai-full-stack-developer",
        "title": "ERP & AI Full Stack Developer",
        "vertical": "MAXEK SOLUTIONS",
        "department": "Engineering",
        "location": "Trivandrum, Kerala, India",
        "employment_type": "",
        "experience": "",
        "posted_on": "2026-08-12",
        "is_internship": False,
        "summary": "Join our engineering team to build advanced ERP and AI solutions.",
        "responsibilities": [],
        "requirements": [],
    },
    {
        "id": "senior-erp-architect",
        "title": "Senior ERP Architect",
        "vertical": "MAXEK SOLUTIONS",
        "department": "Engineering",
        "location": "Trivandrum, Kerala, India",
        "employment_type": "",
        "experience": "",
        "posted_on": "2026-08-12",
        "is_internship": False,
        "summary": "Lead the architectural design and implementation of our enterprise ERP systems.",
        "responsibilities": [],
        "requirements": [],
    },
    {
        "id": "accountant",
        "title": "Accountant",
        "vertical": "MAXEK BUSINESS HUB",
        "department": "Finance",
        "location": "Trivandrum, Kerala, India",
        "employment_type": "",
        "experience": "",
        "posted_on": "2026-08-12",
        "is_internship": False,
        "summary": "Manage financial operations and reporting for the MAXEK group.",
        "responsibilities": [],
        "requirements": [],
    },
    {
        "id": "admin",
        "title": "Admin",
        "vertical": "MAXEK BUSINESS HUB",
        "department": "Administration",
        "location": "Trivandrum, Kerala, India",
        "employment_type": "",
        "experience": "",
        "posted_on": "2026-08-12",
        "is_internship": False,
        "summary": "Support daily administrative and operational functions across our offices.",
        "responsibilities": [],
        "requirements": [],
    },
]
